### ISSUE TITLE
undefined label 'uild/web/index.html  on Mac OS

### ISSUE THREAD

**Issue by farshid-shokrolahi** [doonfrs/flutter-build-web-cache-problem#2]
Hi, thank you for your bash file but I have a problem with the latest version of Flutter
this is my terminal results

`sed: 1: "build/web/flutter.js": undefined label 'uild/web/flutter.js'`

Could you please help me to fix the issue?
I'm using Mac OS 13.0.1

**Comment by farshid-shokrolahi** [comment]
I found the solution.
The  'sed' command acts differently on Linux and Mac OS.
So to fix this issue we have to set the backup file extension after -i

`sed -i .backup "s|<base href=\"/\">|<base href=\"$baseHref\">|g" build/web/index.html`

**Comment by woutervanwijk** [comment]
yes, it's a macos difference. I use this, so you don't get backupfiles:

`sed -i '' "s/\"main.dart.js\"/\"main.dart.js?v=$version\"/g" build/web/flutter.js`

thx for the script!
